### ISSUE TITLE
Great tool! some comments on the web app tool

### ISSUE THREAD

**Issue by chqzeng** [quekky/pyktv#1]
it is THE best KTV open-source I found! great effort to achieve this!

when I tried the web app tool, I see some issues, maybe I did not operate correctly. see screenshots with the explanation in their names here: https://drive.google.com/drive/folders/1n0rxKMWPqIJPKsIy7yD3KXrHwTHKFWU3?usp=sharing
the main program (not via phone) is fine. 

1. failed search by artist.  I notice the `"artist search"` does not work mostly. when search with a given artist name, the result is quite random, esp when Chinese & English artists' names in the same database.  I clicked the `"artist" tab --> "magnifier tool" `--> type in an artist name or name abbreviation--> `click OK`. no specified result sometimes.  during search two items ("all artists",  "all categories") shown on the screen and seems checked but not sure what they are for? 

2. expect better search by title.  when search by title, it works great with title abbreviation, or a single character. for example,  to search for a song title "You raise me up", I can search with "raise", but will fail if I type "You raise". no result. same for 2+ Chinese Characters. any way to improve it?

3. I think it may be the combination of `search by abbreviation`, and `search by name` together that causes the error sometimes. will it possible to replace the `"search by index"` with `"search by name substrings"` to separate these two methods? considering a large database with thousands of songs would be meaningless to search by ID, as no one can remember all the IDs, or if played, then it will in the popular list?

thank you ! it is really a powerful tool,make life more fun !

**Comment by quekky** [comment]
#
